### ISSUE TITLE
Prefix, Suffix and both

### ISSUE THREAD

**Issue by drhus** [bokub/vanity-eth#2]
I noticed all vanity address generator tools out there for Prefix only, while the vast majority of us look on suffix digits to compare, memorize their address 

can't we add this feature to Vanity-Eth? Customize Prefix, or Suffix or both?

**Comment by bokub** [comment]
Yeah, that would be an interesting feature, even if "_the vast majority of us_" seems a little exaggerated.

How do you think the interface would look like? The objective is to keep the UX as simple as possible

**Comment by drhus** [comment]
like ![screenshot of vanity eth _ ethereum vanity address generator](https://user-images.githubusercontent.com/712919/45166249-f401bf00-b1cc-11e8-98ef-b3c86b1f1170.jpg)

possibly instead of xxxxx we put "20 byte / 40 char" which change dynamically with the size of the input, if he input 4 char on prefix the msg on middle will be "18 byte / 36 char" and so on..

the user can select 1) prefix or 2) suffix or 3) both on the same time

**Comment by 0xsabo** [comment]
Can I not choose to have *both* a prefix and a suffix?

**Comment by bokub** [comment]
That's now possible thanks to #57!
