### ISSUE TITLE
Is the Difficulty calculated correctly?

### ISSUE THREAD

**Issue by germartinez** [bokub/vanity-eth#20]
Hello,

This is how I think the *difficulty* should be calculated

- Case-sentive checkbox **is not** selected:

  Each position of the address pattern can take one of these values: `0123456789abcdef` (16 options)
*Difficulty* for pattern `0x1ab` would be 16^3 = 4096

- Case-sentive checkbox **is** selected:

  Each position of the address pattern can take one of these values: `0123456789abcdefABCDEF` (22 options)
*Difficulty* for pattern `0x1ab` would be 22^3 = 10648

Why isn't the web app  calculating the case-sensitive option this way?
For `0x1ab` the app is returning 16384

https://github.com/bokub/vanity-eth/blob/master/src/vue/Statistics.vue#L25

Thank you!

**Comment by bokub** [comment]
Hi ! 
Sorry, I forgot to answer :pensive: 

This is how it works:

- First of all, a "raw address" is generated from a random private key: each position of the address pattern can take one of these values: 0123456789abcdef (16 options), there are no "case" on these
- Then, [I compute](https://github.com/bokub/vanity-eth/blob/master/src/js/vanity.js#L62-L69) the "checksum address" from the raw address. Each letter has a 50% chance to be uppercase, and 50% chance to be lowercase. Numbers are not affected.

Difficulty for a raw address starting with `0x1ab` is 16^3 = 4096, you are correct about that.

Then, if you really want the checksum address to start with `0x1ab` (with lowercase letters), you have to imagine that, in addition to the previous difficutly, you have 4 possibilities for the checksum address:
- `0x1ab...`
- `0x1Ab...`
- `0x1aB...`
- `0x1AB...`

which means the difficulty for the case-sensitive prefix is 4 * 4096 = 16 384

Is it clearer now?

![image](https://user-images.githubusercontent.com/17952318/113871521-49ead900-97b3-11eb-974d-94c2d8a4517d.png)
![image](https://user-images.githubusercontent.com/17952318/113872570-49067700-97b4-11eb-98aa-4c00f6679b03.png)

**Comment by bokub** [comment]
Well, I'm closing this issue
