### ISSUE TITLE
I wonder how to decrypt the private key json file with javascript

### ISSUE THREAD

**Issue by taurusxin** [bokub/vanity-eth#21]
Could you just give the example javascript code.

I' m new in coding. Thanks a lot

**Comment by bokub** [comment]
I don't know, this project encrypts keystores but doesn't encrypt them...

I suggest you Google "decrypt ethereum keystore file", you'll find a lot of answers, such as [this one](https://ethereum.stackexchange.com/questions/47031/how-to-decrypt-private-key-form-keystore-file-without-using-third-party-applica) or [this one](https://wizardforcel.gitbooks.io/practical-cryptography-for-developers-book/content/symmetric-key-ciphers/ethereum-wallet-encryption.html)

Have a pleasant day
