### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by kngspace** [bokub/vanity-eth#22]
Would it be possible to save the results as a csv, as well as specify the number of results requested? For example, have the program look for "deaf", as well as return 15 variations in a csv file? 

I would be happy to donate .1 eth for this as well. 

Thank you,

**Comment by bokub** [comment]
What's sure is that I won't add this feature to Vanity-ETH, because I don't want to clutter the UI with useless features.

However, for 0.1 ETH, I can make a special version of Vanity-ETH just for your need

**Comment by bokub** [comment]
What ? :confused:
