### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by Kawal252** [bokub/vanity-eth#27]
Hi, 

Is it possible to get the output of all the combinations tried & get the output of the same in CSV file.

Thank you,

**Comment by amethvault** [comment]
Hi @bokub ,

Is thier any way to export the same to csv, as when im trying to export the same im getting undefiend error

Thanks,
AM

**Comment by bokub** [comment]
@amethvault please share a screenshot

**Comment by amethvault** [comment]
Please fine the screenshots
![13nov1](https://user-images.githubusercontent.com/92943274/141614161-c31be414-2626-4187-8829-efe762e9bbe5.JPG)
![13nov2](https://user-images.githubusercontent.com/92943274/141614176-d91d0c60-3386-4d23-9914-7075ab41fe67.JPG)
![13nov3](https://user-images.githubusercontent.com/92943274/141614191-566fafe0-832b-4d74-b9b3-468721b6e94c.JPG)

**Comment by bokub** [comment]
I still don't know what your problem is..

**Comment by amethvault** [comment]
Well I wanted to ask is is this the way and correct place to export it to csv files?
