### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by wojake** [bokub/vanity-eth#28]
Add a timer;

This timer will showcase the user's time spent to generate the vanity address, some vanity addresses are **very** long, it would be very beneficial.

Make sure the timer could facilitate `Days` too, thanks.
```
00:00:00 
Day:Hour:Minute
```

![saveme](https://user-images.githubusercontent.com/87929946/142592632-6d93b128-9738-49ff-aae8-c289c84c6fc4.PNG)

**Comment by bokub** [comment]
Hello @wojake 

Thank you for your suggestion.

**Comment by bokub** [comment]
I've added the time needed to reach a 50% probability.

**N.B**: It will be displayed only when speed is not 0 (when Vanity-ETH is running or was running before)

![image](https://user-images.githubusercontent.com/17952318/143067515-7ef1679c-89bd-428c-92e5-b78d5f85b2f6.png)
