### ISSUE TITLE
Vanity Contract Address

### ISSUE THREAD

**Issue by Siul293** [bokub/vanity-eth#30]
It would be great if you can add this feature.

- Get the wallet private key that in a requested nonce will generate a custom vanity address. 
   I.e.  Contract starting with 0xbad..... in the wallet nonce 2

Thanks.

**Comment by 9-9-9-9** [comment]
This project is kinda `brute-force` so it is unable to do it with contract since you must deploy millions/billions contracts to fit your need. Nowadays, deploy a contract into ETH main net costs around $800 each

**Comment by Siul293** [comment]
Wut? @9-9-9-9 The addresses are also calculated via brute force, the only two factors to consider to calculate the contrac address are the deployer wallet addres and the wallet nonce, so

**Comment by 9-9-9-9** [comment]
@Siul293 idk about this, thanks man

**Comment by bokub** [comment]
I currently don't have enough knowledge about contracts and contracts addresses, but I might work on it someday if I find enough free time.

**Comment by 9-9-9-9** [comment]
@Siul293 I see, so the target is to generate an address with ability to deploy a `vanity contract` at nonce 2

Or better if can generate a `vanity address` with ability to deploy a `vanity contract` at nonce 2

Is that right?

**Comment by Siul293** [comment]
@9-9-9-9 the target is generating an address with the ability to deploy a vanity contract in a given nonce.

**Comment by 9-9-9-9** [comment]
hey man @bokub , it's good to go now

```
const rlp = require('rlp');
const util = require('ethereumjs-util');

const addr = '0x6ac7ea33f8831ea9dcc53393aaa88b25a785dbf0'
const addressAsBytes = util.toBuffer(addr);

for (let nonce = 0; nonce <= 3; nonce++) {
    let calculatedAddressAsBytes = util.keccak256(util.arrToBufArr(rlp.encode([addressAsBytes, nonce]))).slice(12);
    console.log(`nonce${nonce}= "0x${calculatedAddressAsBytes.toString('hex')}"`);
}

/* Output:
nonce0= "0xcd234a471b72ba2f1ccf0a70fcaba648a5eecd8d"
nonce1= "0x343c43a37d37dff08ae8c4a11544c718abb4fcf8"
nonce2= "0xf778b86fa74e846c4f0a1fbd1335fe81c00a0c91"
nonce3= "0xfffd933a0bc612844eaf0c6fe3e5b8e9b6c1d19c"
*/
```

Test case from [here](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed) referenced by @Siul293

**Comment by 9-9-9-9** [comment]
@Siul293 hey, it's here
https://github.com/9-9-9-9/Vanity-ERC20-Contract-Address-Generator

**Comment by bokub** [comment]
If you don't mind using a command-line tool, MyEtherWallet's [VanityEth](https://github.com/MyEtherWallet/VanityEth) also supports contract addresses.

**Comment by Siul293** [comment]
Great !!! Thanks
