### ISSUE TITLE
threads

### ISSUE THREAD

**Issue by Imperator69** [bokub/vanity-eth#32]
what do the "threads" do? 

its not described anywhere :-(

**Comment by bokub** [comment]
Hello,

It **is** described, but I agree that the explanation is a little bit light.

![image](https://user-images.githubusercontent.com/17952318/153019339-0e5d5d7a-8bcc-4dbf-b0ec-574e1549a6e3.png)

Basically, your computer CPU has a certain number of "[threads](https://en.wikipedia.org/wiki/Thread_(computing))", and each one of them can do a task in parallel of the others.

For example, if your computer has 8 threads, you can dedicate all of them to Vanity-ETH, or you can allocate only 6 to keep 2 threads "free" for other tasks, making your computer look less "busy".
You can also choose 16 threads in the options, but if you only have 8, each one of your CPU threads will have to alternate between two Vanity-ETH instances, which is not optimal.

**Comment by bokub** [comment]
I'm closing this issue. If you still have questions, don't hesitate to ask.
