### ISSUE TITLE
Get Mnemonic Phrase?

### ISSUE THREAD

**Issue by c0ntrite** [bokub/vanity-eth#34]
Is it possible to get the mnemonic phrase out of this?

**Comment by 9-9-9-9** [comment]
Hi, no, it's impossible.

Mnemonic Phase is parent of Private Key, a mnemonic phase can generate millions private keys

https://ethereum.stackexchange.com/questions/62530/how-can-i-get-a-mnemonic-phrase-from-a-private-key

**Comment by bokub** [comment]
Thanks @9-9-9-9 !
