### ISSUE TITLE
Introduce my project based on vanity-eth project with performance increased

### ISSUE THREAD

**Issue by 9-9-9-9** [bokub/vanity-eth#36]
[Visit my Github repo](https://github.com/9-9-9-9/Vanity-ETH-Address-Generator)

or [Vanity ERC20 contract address generator](https://github.com/9-9-9-9/Vanity-ERC20-Contract-Address-Generator)
---
#### Some reasons about why this project was created
1. Vanity-ETH runs on browser so it can not run on maximum speed as the code can
2. Can only select one pattern to match so it would wastes a lot of nice-looking addresses
3. Will stop after specific pattern found (I don't like it because I want more and compare what is better)

So I decided to extract some lines of code from the Vanity-ETH project and create a custom project which can resolves the above problems. The result is good, my PC can generate around 75k addr/s while maximum 14k addr/s on [vanity-eth.tk](https://vanity-eth.tk/)

But this project doesn't have UI, it runs code directly with nodejs thus:

> This project requires user has a little bit experience in programming because you must edit some lines in script files to match your requirement as well as it doesn't have an user interface, everything must be done via text editor and terminal

With `32 cores` 32gb of RAM machine on GCP with 32 processes, I can generate `320k addr/s` (10k/s each process) and generated
| Number of addresses generated within 20 hours | Description |
|----|----|
| 2 addr | 9 digits match my level2 patterns |
| 6 addr | 10 score |
| 61 addr | 9 score |
| 488 addr | 8 score |
| 554 addr | 7 score |
| 8176 addr | 6 score |

**Comment by 9-9-9-9** [comment]
Yep, I'm gonna do it when I have more free time. Currently I just made it for myself and share to guys

**Comment by bokub** [comment]
Hi,
Did you delete your project?

**Comment by TaoistWorld** [comment]
Hi @bokub [it was moved](https://github.com/TaoistWorld/Vanity-ETH-Contract-Address-Generator). Thanks for your suggestion, it now has cli, easier to use

**Comment by 9-9-9-9** [comment]
Btw @bokub contract gen code is [here](https://github.com/bokub/vanity-eth/issues/30#issuecomment-1057284485) It would be so great if you can bring it to the web UI, I guess many users would love it

**Comment by bokub** [comment]
> It would be so great if you can bring it to the web UI

I may work on this someday! I just need to find some free time
