### ISSUE TITLE
Paid help

### ISSUE THREAD

**Issue by zhaocaijinbao1314** [bokub/vanity-eth#37]
Can you help me make a program that can generate Trc20 wallet address, like this ETH

**Comment by bokub** [comment]
Hi,

What's your budget?

**Comment by zhaocaijinbao1314** [comment]
You can tell me a price and the time required. I do this to have a good trx address.> Hi,
> 
> 
> 
> What's your budget?

**Comment by zhaocaijinbao1314** [comment]
Waiting for your reply online.
________________________________
发件人: Boris K ***@***.***>
发送时间: Thursday, March 10, 2022 2:25:19 AM
收件人: bokub/vanity-eth ***@***.***>
抄送: zhaocaijinbao1314 ***@***.***>; Author ***@***.***>
主题: Re: [bokub/vanity-eth] Paid help (Issue #37)


Hi,

What's your budget?

―

**Comment by bokub** [comment]
Replied to you by e-mail

**Comment by zhaocaijinbao1314** [comment]
Do you know my email address?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Boris K ***@***.***>
发送时间: Thursday, March 10, 2022 3:17:33 AM
收件人: bokub/vanity-eth ***@***.***>
抄送: zhaocaijinbao1314 ***@***.***>; Author ***@***.***>
主题: Re: [bokub/vanity-eth] Paid help (Issue #37)


Replied to you by e-mail

―
