### ISSUE TITLE
Change code in file src/js/vanity.js does not apply

### ISSUE THREAD

**Issue by helloairdrop** [bokub/vanity-eth#41]
Hi there, 
I am trying to learn and also test something on this source code
But when I try to change code in src/js/vanity.js, the app never reloads and the new code doesn't apply as well

I am not sure why it's happen, I think some config there I doesn't understand
Could you help?

Reproduce:
+ download source code and extract
+ **yarn** (install package)
+ **yarn serve** (run source code and it is working on port 8080)

**Comment by bokub** [comment]
Hello,

Can you please provide an example of what you changed in `vanity.js`, so I can test with the exact same conditions?

Also, did you see any warning or error in the console where you run `yarn serve` ?

**Comment by helloairdrop** [comment]
Hello,

I added some new code like log: `console.log('call to vanity js file')` under line 6 in **vanity.js** file or another in **onmessage** fuction:  `console.log('onmessage emit')`

When I am running with` yarn serve` there is no error or warning and I tried to run with `npm ` (deleted `node_modules ` ), it never reloads and applys new code on the app as well (same `yarn`)

Reproduce: 
1. get the source code on github
2. run `npm i`
3. run `npm run serve` (it's working on port 8080)
4. change some code in `vanity.js` file, like `console.log('checking the changes')` then save **(the app doesn't reload and the new code doesn't apply)**
5. try again to change some code

I found some config can help it reload and apply the new code: https://stackoverflow.com/questions/60069459/npm-run-build-without-cache-folder-in-node-modules, we can add this code into file `vue.config.js`, it will delete cache whenever we change the code
   ```
 config.module.rule('vue').uses.delete('cache-loader');
 config.module.rule('js').uses.delete('cache-loader');

```

Not sure this is the good solution or not, if you have better solution, could you share me?
Thank you!!!

![image](https://user-images.githubusercontent.com/74862848/173283353-155b65fb-7421-4a32-b1ed-b02556922182.png)

**Comment by helloairdrop** [comment]
Thank you for your reply,

I added comment on github already

Could you help to check it?

Vào Th 2, 13 thg 6, 2022 vào lúc 00:01 Boris K ***@***.***>
đã viết:
