### ISSUE TITLE
private key security 

### ISSUE THREAD

**Issue by hcocoa** [bokub/vanity-eth#44]
Just read about [profanity](https://github.com/johguse/profanity) incident. 

Please check https://github.com/bokub/vanity-eth/blob/620a2c198010ccf56e8f60baccbf94ed74b15bf6/src/js/vanity.js#L21

Does this project have the similar problem? Is 32 bytes enough for a private key?

**Comment by bokub** [comment]
> Does this project have the similar problem?

No, it doesn't have a similar problem

> Is 32 bytes enough for a private key?

32 bytes is literally the size of a Ethereum private key, so yes, it's enough and could not be higher even if I wanted to.

Profanity uses 32 **bit** seeds, which is the same as 4 **bytes**.

Please read #43 for more details

**Comment by hcocoa** [comment]
thanks for the reply

**Comment by Favourjacobmudiaga** [comment]
Good
