### ISSUE TITLE
Calculation-heavy webpage crashe,error code "out of memory"

### ISSUE THREAD

**Issue by zhangguorong1995** [bokub/vanity-eth#47]
I bought a high-performance VPS,  64core, 64G memory, I use offline, online, build, and npm run serve, and I get "out of memory".
Observe the memory situation. After using about 12G of memory, the page crashes. I tried to pass in --max-old-space-size=49000 and it didn't have any effect.

error：
<img width="831" alt="image" src="https://user-images.githubusercontent.com/22090495/197173490-7bca4776-9d8f-47ba-8929-4cea8af3b7fc.png">

work：
![image](https://user-images.githubusercontent.com/22090495/197173641-c173f5a1-c68a-4a54-996d-7b63dce5bbf5.png)

**Comment by zhangguorong1995** [comment]
node -v
v16.18.0

**Comment by bokub** [comment]
First of all: Hello!

The "out of memory" in your screenshot means your browser is out of memory, not your server. Node parameters won't change anything.

Also, `npm run serve` runs a **development** sever which includes lots of debugging features, and takes a lot of server RAM & browser RAM. That could explain your problem.

**Comment by zhangguorong1995** [comment]
So the question is browser RAM?Do you have any good solution? I see that running the program requires opening the browser web，Thanks.

**Comment by bokub** [comment]
Yes Vanity-ETH runs only in the browser. It's a tool designed to be easy to use, for users who don't want to spend time installing technical stuff and don't need exceptional performance 

If you have the technical ability and the patience to buy a dedicated VPS, maybe you should use another tool which will probably offer better performances.

**Comment by zhangguorong1995** [comment]
OK，thanks
