### ISSUE TITLE
Add first deployed smart contract address evaluation [Feature Request]

### ISSUE THREAD

**Issue by k06a** [bokub/vanity-eth#5]

**Comment by bokub** [comment]
Can you explain, please?

**Comment by k06a** [comment]
https://github.com/MyEtherWallet/VanityEth/blob/master/libs/VanityEth.js#L36:
```
var getDeterministicContractAddress = function(address, nonce = 0) {
    return '0x' + ethUtils.sha3(ethUtils.rlp.encode([address, nonce])).slice(12).toString('hex');
}
```

I would like to generate wallet which will deploy its first smart contract to a pretty address.

**Comment by bokub** [comment]
Vanity-ETH doesn't support contract addresses, and that feature is not planned, I'm sorry.

Here is what you can do:
- Clone the project
- Run `npm i`
- Edit [`vanity.js`](https://github.com/bokub/vanity-eth/blob/master/src/js/vanity.js#L36) according to your needs
- Run `npm run dev` to use your version of vanity-ETH locally.
