### ISSUE TITLE
Add a pause function [feature request]

### ISSUE THREAD

**Issue by addmins** [bokub/vanity-eth#7]
1. Add a pause function to prevent the previous hashes wasted. 
2. Change the stop button into 'force stop'.
3. Give a popup to ask the user to ask if they 'really' want to stop the program, and tell them 
"the action cannot be undone. It will progress will reset once the generate button is pressed."
Please fix at least one of these issues before changing it to resolved.

**Comment by bokub** [comment]
I don't think you understand how it works.
This
![image](https://user-images.githubusercontent.com/17952318/53186516-6a6e6e00-3601-11e9-8b8a-410fd5c8dcf0.png)
does not represent a progression, but only a probability.

Finding a vanity address __is just testing lots of random private keys until one of them works__, you can never know when you're going to end, you can only *estimate* it.

You don't "start over" if you press stop, you just reset the estimation.
You can totally stop the process at 80%, hit run again and find an address at 10%.

Is it clearer ?

**Comment by addmins** [comment]
Cool! I will now close this issue...
