### ISSUE TITLE
Suggestion - add ability to display password

### ISSUE THREAD

**Issue by AleksandarFilipov** [bokub/vanity-eth#8]
I like the idea of a small offline generator. It would had been great it the password on download was visible. If's nice to verify that you've typed what you intended.

https://github.com/bokub/vanity-eth/blob/master/src/vue/Save.vue#L8

**Comment by frank-dspeed** [comment]
@AleksandarFilipov little geek tip from me type your password for example in your browser address bar then you use your mouse to move it into the password fild. 
you can also use strg +x and strg + v to cut and paste it but this way it lands in the clipboard so you need to think if that is good or not depends on how often you clean it

**Comment by bokub** [comment]
I've (finally) added the feature! 🎉

Thanks for your suggestion
